name: 'Build and push Docker image with a model running in Ollama'
description: 'Automates the process of building an pushing a Docker image that includes a specified model running in Ollama'
inputs:
  platform:
    description: 'Platform'
    required: true
  docker_username:
    description: 'DockerHub username'
    required: true
  docker_password:
    description: 'DockerHub password'
    required: true
  docker_repository:
    description: 'DockerHub repository name'
    required: true
  docker_tag:
    description: 'DockerHub image tag'
    required: true
  model_name:
    description: 'model name'
    required: true
  model_tag:
    description: 'model tag (optional)'
    required: false
    default: 'latest'
  ollama_version:
    description: 'Ollama version (optional)'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker info
      shell: bash
      run: docker info
    - name: Buildx inspect
      shell: bash
      run: docker buildx inspect

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        file: Dockerfile
        platforms: ${{ inputs.platform }}
        push: true
        tags: ${{ inputs.docker_username }}/${{ inputs.docker_repository }}:${{ inputs.docker_tag }}
        build-args: |
          MODEL_NAME=${{ inputs.model_name }}
          MODEL_TAG=${{ inputs.model_tag }}        
          OLLAMA_VERSION=${{ inputs.ollama_version }}
