name: 'Dockerize Ollama models'

on:
  workflow_dispatch:
    inputs:
      ollama_version:
        description: 'Ollama version'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          - name: 'nemotron-mini'
            tag: '4b'
            description: 'A commercial-friendly small language model by NVIDIA optimized for roleplay, RAG QA, and function calling'
          - name: 'smollm'
            tags: ['135m', '360m', '1.7b']
            description: 'A family of small models with 135M, 360M, and 1.7B parameters, trained on a new high-quality dataset'
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Docker Image
        run: |
          for tag in ${{ matrix.model.tags || matrix.model.tag }}; do
            echo "Building Docker image for model ${{ matrix.model.name }} with tag $tag"
            ./build_docker_image.sh \
              --username ${{ secrets.DOCKER_USERNAME }} \
              --password ${{ secrets.DOCKER_PASSWORD }} \
              --repository ${{ matrix.model.name }} \
              --tag ${{ github.event.inputs.ollama_version }}-$tag \
              --model-name ${{ matrix.model.name }} \
              --model-tag $tag \
              --ollama-version ${{ github.event.inputs.ollama_version }} \
              --description "${{ matrix.model.description }}"
          done
