name: 'Dockerize Ollama model'

on:
  workflow_dispatch:
    inputs:
      ollama_version:
        description: 'Ollama version'
        required: false
      short_description:
        description: 'Short description'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Docker Image
        uses: ./
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          docker_repository: spring-ai-demo-models
          docker_tag: ${{ github.event.inputs.ollama_version }}
          ollama_version: ${{ github.event.inputs.ollama_version }}
          short_description: ${{ github.event.inputs.short_description }}
